apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-infotrygd
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{image}}
  port: 8080 # Required. The port number which is exposed by the container and should receive HTTP traffic.
  liveness: # HTTP endpoint that signals 200 OK when the application is running.
    path: /actuator/health
    initialDelay: 10
    timeout: 1
    periodSeconds: 5     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 10 # when a Pod starts and the probe fails,
      # nais will try failureThreshold times before giving up and restarting the Pod
    # Defaults to 3
  readiness: # HTTP endpoint that signals 200 OK when it is okay to start routing traffic to the application.
    path: /actuator/health
    # /rest/internal/isAlive
    initialDelay: 20
    timeout: 1
  replicas: # Optional. Set min = max to disable autoscaling.
    min: 1 # minimum number of replicas.
    max: 1 # maximum number of replicas.
    cpuThresholdPercentage: 50 # total cpu percentage threshold on deployment, at which point it will increase number of pods if current < max
  prometheus: # Optional.
    enabled: true # if true the pod will be scraped for metrics by prometheus
    path: /actuator/prometheus # Path to prometheus-metrics
    # /actuator/prometheus
  resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
    limits:
      memory: 512Mi  # app will be killed if exceeding these limits
    requests: # App is guaranteed the requested resources and  will be scheduled on nodes with at least this amount of resources available
      cpu: 100m
      memory: 512Mi
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  ingresses:
  - https://familie-ks-infotrygd.dev-fss-pub.nais.io
  - https://familie-ks-infotrygd.dev.intern.nav.no/
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/ks_infotrygd_q1-user
        mountPath: /var/run/secrets/oracle/creds
  accessPolicy:
    inbound:
      rules:
        - application: "bidrag-grunnlag"
          namespace: bidrag
          cluster: dev-gcp
        - application: "bidrag-grunnlag-feature"
          namespace: bidrag
          cluster: dev-gcp
        - application: "familie-ks-sak"
          namespace: teamfamilie
          cluster: dev-gcp
        - application: "familie-baks-mottak"
          namespace: teamfamilie
          cluster: dev-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b"
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"  # 0000-GA-STDAPPS
          - id: "71f503a2-c28f-4394-a05a-8da263ceca4a"  # VEILEDER_ROLLE
          - id: "c7e0b108-7ae6-432c-9ab4-946174c240c0"  # SAKSBEHANDLER_ROLLE
          - id: "52fe1bef-224f-49df-a40a-29f92d4520f8"  # BESLUTTER_ROLLE

      tenant: trygdeetaten.no
      replyURLs:
        - "https://familie-ks-infotrygd.dev.intern.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  env:
    - name: "APP_DATASOURCE_URL"
      value: "jdbc:oracle:thin:@a01dbfl033.adeo.no:1521/infotrygd_ksq"
    - name: "APP_DATASOURCE_PLATFORM"
      value: "org.hibernate.dialect.OracleDialect"
    - name: "APP_DATASOURCE_DRIVER"
      value: "oracle.jdbc.driver.OracleDriver"
    - name: "APP_JPA_PLATFORM"
      value: "org.hibernate.dialect.OracleDialect"
    - name: "APP_DEFAULT_SCHEMA"
      value: "INFOTRYGD_KSQ"
    - name: "APP_DATASOURCE_USERNAME_PATH"
      value: "/var/run/secrets/oracle/creds/username"
    - name: "APP_DATASOURCE_PASSWORD_PATH"
      value: "/var/run/secrets/oracle/creds/password"
    - name: "APP_DDL_AUTO"
      value: "none"
    - name: "APP_AZURE_PROXY_URL"
      value: "https://webproxy-nais.nav.no:8088"
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
