server.port: 8080

spring:
  main:
    banner-mode: "off"
  application:
    name: ${NAIS_APP_NAME:familie-ks-infotrygd}
  datasource:
    url: ${APP_DATASOURCE_URL}
    driver-class-name: ${APP_DATASOURCE_DRIVER}
  jpa:
    database-platform: ${APP_JPA_PLATFORM}
    hibernate:
      ddl-auto: ${APP_DDL_AUTO:validate}
    properties:
      hibernate:
        default_schema: ${APP_DEFAULT_SCHEMA}
  sql:
    init:
      platform: ${APP_DATASOURCE_PLATFORM}

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

#oidc...
http.proxy.parametername: notused

no.nav.security.jwt:
  expirythreshold: 60 #threshold in minutes until token expires
  issuer:
    azuread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
      proxyurl: ${APP_AZURE_PROXY_URL}

springdoc:
  packages-to-scan: "no.nav.infotrygd.kontantstotte"
  paths-to-match: "/api/**"
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: ${AZURE_APP_CLIENT_ID}
      scope-separator: ","
    disable-swagger-default-url: true

vault:
  password: "/var/run/secrets/oracle/creds/password"
  username: "/var/run/secrets/oracle/creds/username"

# Swagger
AUTHORIZATION_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/authorize
TOKEN_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
API_SCOPE: api://${AZURE_APP_CLIENT_ID}/.default

TEAMFAMILIE_FORVALTNING_GROUP_ID: "c7e0b108-7ae6-432c-9ab4-946174c240c0"

TEAMFAMILIE_SAKSBEHANDLER_GROUP_ID: "c7e0b108-7ae6-432c-9ab4-946174c240c0"  # SAKSBEHANDLER_ROLLE
TEAMFAMILIE_BESLUTTER_GROUP_ID: "52fe1bef-224f-49df-a40a-29f92d4520f8"  # BESLUTTER_ROLLE