name: Build-Deploy-Prod-GCP
on:
  push:
    branches:
      - 'main'
env:
  IMAGE: ghcr.io/navikt/familie-ks-infotrygd:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/navikt/familie-ks-infotrygd:latest
jobs:
  deploy-to-prod:
    name: Bygg app/image, push til github, deploy til dev-fss og prod-fss
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Test and build
        env:
          GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean verify
      - name: Build docker image
        run: |
          docker build -t $IMAGE .
      - name: Push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE}
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss.yml
      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/prod-fss.yml