name: Build-Deploy-Prod-GCP
on:
  push:
    branches:
      - 'main'

permissions:
  contents: "read"
  id-token: "write"

jobs:
  deploy-to-prod:
    name: Bygg app/image, push til github, deploy til dev-fss og prod-fss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Test and build
        env:
          GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean verify
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamfamilie
          tag: latest
          push_image: true
          dockerfile: Dockerfile
          docker_context: .
          byosbom: target/classes/META-INF/sbom/application.cdx.json
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss.yml
          VAR: image=${{ steps.docker-push.outputs.image }}
      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: nais/prod-fss.yml
          VAR: image=${{ steps.docker-push.outputs.image }}